title: Mwayi Sosola # your name (or website title) here
logo: "C:\Users\mwayi\Downloads\MS_Logo.png"
description: > # your text below (remove <br> elements if you don't need line breaks)

  <br>Hello, I’m Mwayi, a Business Analyst with over 9 years of experience and a strong background in data. I am driven by my passion for problem solving  and turning complex data into business insights that drive business improvement.  In addition to my Business Analyst skills, I have also added additional skills that enable me to effectively perform the tasks of a Data Analyst. I have experience working with data via SQL, Python and I have gained valuable exposure using visual tools such as Tableau to graphically represent my analysis in a way that is insightful to decision makers.<br>
  
  <br>Most recently, I made use of my data analytics skills to identify and group commercial customers who were least and most likely at risk of defaulting on their loans.<br>
  
  <a href="https://www.linkedin.com/in/mwayi-s-9a1929223/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-DWHNJVBGW6 # your Google Analytics tracking ID here
