title: Mwayi Sosola # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br>Hello, I am Mwayi<br>
  Second description 
  <br>I am a proficiently skilled data analyst in Python, SQL and Tableau who enjoys problem solving and using data to tell meaningful stories<br>
  <a href="https://www.linkedin.com/in/mwayi-s-9a1929223/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-DWHNJVBGW6 # your Google Analytics tracking ID here
