title: Mwayi Sosola # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  <br>Hello, I’m Mwayi, a Business Analyst with over 9 years of experience and a strong background in data. I am driven by my passion for problem solving  and turning complex data into business insights that drive business improvement.  In addition to my Business Analyst skills, I have also added additional skills that enable me to effectively perform the tasks of a Data Analyst. I have experience working with data via SQL, Python and I have gained valuable exposure using visual tools such as Tableau to graphically represent my analysis in a way that is insightful to decision makers.<br>
  
  <br>In my most recent role I made use of my data analytics skills to identify and group commercial customers who were least and most likely at risk of defaulting on their loans. This gave the Relationship Managers the insight to proactively  engage with their clients. I aspire to continually add value to any organisation that I work for using the experience and skills that I have acquired over my career thus far.<br>
  
  <a href="https://www.linkedin.com/in/mwayi-s-9a1929223/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-DWHNJVBGW6 # your Google Analytics tracking ID here
